// Localhost Requests
### Get All
GET http://localhost:3000/contacts HTTP/1.1

### Get By ID

GET http://localhost:3000/contacts/66f1c80632da1a7d886f0fd1 HTTP/1.1


### Create contact
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Coquito",
    "lastName": "Sanabria",
    "email": "coq@gmail.com",
    "favoriteColor": "Yellow",
    "birthday": "01/01/2020"
}

### Update contact
PUT http://localhost:3000/contacts/6701f5343ddc1d8a6e3996b8 HTTP/1.1
content-type: application/json

{
    "firstName": "Coquito",
    "lastName": "Sanabria",
    "email": "coq@gmail.com",
    "favoriteColor": "Yellow",
    "birthday": "01/02/2020"
}


### Delete contact
DELETE http://localhost:3000/contacts/6701f5a23ddc1d8a6e3996b9 HTTP/1.1


###
// -------------------
// -------------------
// -------------------
// Render Requests
### Get All

GET https://cse341-webservices-2j5w.onrender.com/contacts HTTP/1.1

### Get By ID

GET https://cse341-webservices-2j5w.onrender.com/contacts/66f1c80632da1a7d886f0fd1 HTTP/1.1

### Create contact
POST https://cse341-webservices-2j5w.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Coquito",
    "lastName": "Sanabria",
    "email": "coq@gmail.com",
    "favoriteColor": "Yellow",
    "birthday": "01/01/2020"
}

### Update contact
PUT https://cse341-webservices-2j5w.onrender.com/contacts/6701f809edb99c6202db3624 HTTP/1.1
content-type: application/json

{
    "firstName": "Coquito",
    "lastName": "Sanabria",
    "email": "coq@gmail.com",
    "favoriteColor": "Yellow",
    "birthday": "01/02/2020"
}

### Delete contact
DELETE https://cse341-webservices-2j5w.onrender.com/contacts/6701f809edb99c6202db3624 HTTP/1.1

